version: "3"
services:
  cacti:
    container_name: vuln-cacti
    build:
      dockerfile: Dockerfile_cacti
    ports:
      - 1337:80
    depends_on:
      - cacti_db
    restart: always
  cacti_db:
    container_name: vuln-cacti-mysql
    build:
      dockerfile: Dockerfile_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: cacti_mysql
      MYSQL_USER: cacti_mysql_user
      MYSQL_PASSWORD: cacti_mysql_password
    restart: always
